{
 "title": "Network DMS Brugge | Live",
 "tags": [ "ntop" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Geo Heatmap",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "country:traffic",
     "query": "SELECT bytes_egress,bytes_ingress,country FROM \"country:traffic\" WHERE (\"ifid\" = '7') AND $timeFilter GROUP BY country fill(null)",
     "select": [
      [
       { "params": [ "bytes_ingress" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "WAN (Proximus)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Traffic IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Traffic OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.62" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Applications",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": " ",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "protocol" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi",
     "query": "SELECT mean(\"num_flows\") FROM \"autogen\".\"iface:ndpi_flows\" WHERE (\"ifid\" = '7') AND $timeFilter GROUP BY time($__interval), \"protocol\" fill(null) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN - Live Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:traffic",
     "query": "SELECT non_negative_derivative(last(\"bytes\"), 1s) * 8 FROM \"autogen\".\"iface:traffic\" WHERE (\"ifid\" = '7') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Per VLAN - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "VLAN 0 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 10 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "10" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 100 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "100" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 105 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "105" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 120 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "120" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 130 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "130" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 200 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "200" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 15 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "15" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 40 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "40" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 70 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "70" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "VLAN 90 - RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vlan:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 10s) FROM \"vlan:traffic\" WHERE (\"vlan\" = '0' AND \"ifid\" = '7') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vlan", "operator": "=", "value": "90" },
      { "condition": "AND", "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN - Live Hosts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "iface:hosts",
     "select": [
      [
       { "params": [ "num_hosts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN - Live Flows",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:flows",
     "select": [
      [
       { "params": [ "num_flows" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Verhouding UDP/TCP/ICMP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TCP RAW",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:l4protos",
     "query": "SELECT mean(\"bytes_egress\") FROM \"host:l4protos\" WHERE (\"l4proto\" = 'tcp' OR \"l4proto\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "tcp" }
     ]
    },
    {
     "alias": "ICMP RAW",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:l4protos",
     "query": "SELECT mean(\"bytes_egress\") FROM \"host:l4protos\" WHERE (\"l4proto\" = 'tcp' OR \"l4proto\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "icmp" }
     ]
    },
    {
     "alias": "UDP RAW",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "host:l4protos",
     "query": "SELECT mean(\"bytes_egress\") FROM \"host:l4protos\" WHERE (\"l4proto\" = 'tcp' OR \"l4proto\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "l4proto", "operator": "=", "value": "udp" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN - HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "traffic",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iface:ndpi",
     "query": "SELECT non_negative_derivative(mean(\"bytes\"), 1s)  * 8 FROM \"autogen\".\"iface:ndpi\" WHERE (\"ifid\" = '7' AND \"protocol\" = 'HTTP') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " * 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "protocol", "operator": "=", "value": "HTTP" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN - Packets / Drops",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "TOTAL PACKETS RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "iface:packets_vs_drops",
     "select": [
      [
       { "params": [ "packets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "TOTAL DROPS RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "iface:packets_vs_drops",
     "select": [
      [
       { "params": [ "drops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "Interface SPAN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "alias": "Interface eno50",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "iface:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes\"), 1s)  *8 FROM \"autogen\".\"iface:traffic\" WHERE (\"ifid\" = '0') AND $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " *8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ifid", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  { "title": "Uplinks Distri and up", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Core to firewall",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "S0-01-to-Fortigate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.61" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "49" }
     ]
    }
   ]
  },
  {
   "title": "D1-01 to S0-01 (Core)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.61" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "107" }
     ]
    }
   ]
  },
  {
   "title": "D0-01 to S0-01 (Core)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.61" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "328" }
     ]
    }
   ]
  },
  { "title": "Uplinks Access to Distri", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "C2 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.240" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "15" }
     ]
    }
   ]
  },
  {
   "title": "D1-03 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.240" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1013" }
     ]
    }
   ]
  },
  {
   "title": "D1-02 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.240" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1012" }
     ]
    }
   ]
  },
  {
   "title": "D2-01 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.240" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "16" }
     ]
    }
   ]
  },
  {
   "title": "D0-02 to D0-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.246" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "96" }
     ]
    }
   ]
  },
  {
   "title": "C0 to D0-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.246" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "70" }
     ]
    }
   ]
  },
  {
   "title": "A2b to D0-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.246" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "95" }
     ]
    }
   ]
  },
  {
   "title": "C1-02 to D0-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.246" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "93" }
     ]
    }
   ]
  },
  {
   "title": "Uplinks Wireless Infra (Switches)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "USW-D0 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.101" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
     ]
    }
   ]
  },
  {
   "title": "USW-D1 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.111" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
     ]
    }
   ]
  },
  {
   "title": "USW-C1 to D1-01 (DISTR)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.112" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "9" }
     ]
    }
   ]
  },
  {
   "title": "USW-Zolder to S0-01 (Core)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.131" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
     ]
    }
   ]
  },
  {
   "title": "USW-L4 to S0-01 (Core)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "8" }
     ]
    }
   ]
  },
  { "title": "Uplinks Wireless Infra (APs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "U6-LR-C0-Pacific",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.112" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D0-Online",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.101" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D0-Keuken",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.101" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D0-Bistro",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.101" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D0-CFO",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.101" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-C1-Mathias",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.112" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D1-Keuken",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.111" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "5" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D1-Arne",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.111" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-C2-Creatie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.112" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D1-Vergaderzalen",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.111" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-C1-Sales",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.111" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-D2-OM-Video",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.0.61" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "66" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Printing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Fotostudio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "4" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Fitness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.131" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Zolder",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.131" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Loods2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Loods3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "5" }
     ]
    }
   ]
  },
  {
   "title": "U6-LR-Loods4-Laadkades",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_if:traffic",
     "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_rcvd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "192.168.24.132" },
      { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  { "title": "Hardware data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "CPU load - Synology",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp_dev:cpu_states",
     "select": [
      [
       { "params": [ "system_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historical Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uplink Historical Data",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "WAN IN",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.62" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "WAN OUT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.62" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "CORE TO WAN DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.61" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "49" }
       ]
      },
      {
       "alias": "D1-01 to S0-01 (Core) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.61" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "107" }
       ]
      },
      {
       "alias": "D0-01 to S0-01 (Core) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.61" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "328" }
       ]
      },
      {
       "alias": "C2 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.240" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "15" }
       ]
      },
      {
       "alias": "D1-03 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.240" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1013" }
       ]
      },
      {
       "alias": "D1-02 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.240" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1012" }
       ]
      },
      {
       "alias": "D2-01 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.240" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "16" }
       ]
      },
      {
       "alias": "D0-02 to D0-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.246" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "96" }
       ]
      },
      {
       "alias": "C0 to D0-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.246" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "70" }
       ]
      },
      {
       "alias": "A2b to D0-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.246" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "95" }
       ]
      },
      {
       "alias": "C1-02 to D0-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"IN\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"OUT\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.24.101' AND \"if_index\" = '25') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.246" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "93" }
       ]
      }
     ]
    },
    {
     "title": "Uplink Wireless Infra (Switches)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "USW-D0 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.101" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
       ]
      },
      {
       "alias": "USW-D1 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.111" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
       ]
      },
      {
       "alias": "USW-C1 to D1-01 (DISTR) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.112" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "9" }
       ]
      },
      {
       "alias": "USW-Zolder to S0-01 (Core) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.131" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "25" }
       ]
      },
      {
       "alias": "USW-L4 to S0-01 (Core) DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "8" }
       ]
      }
     ]
    },
    {
     "title": "Application V2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "alias": " ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "protocol" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "iface:ndpi",
       "query": "SELECT mean(\"num_flows\") FROM \"autogen\".\"iface:ndpi_flows\" WHERE (\"ifid\" = '7') AND $timeFilter GROUP BY time($__interval), \"protocol\" fill(null) ORDER BY time DESC",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "ifid", "operator": "=", "value": "7" }
       ]
      }
     ]
    },
    {
     "title": "Uplink Wireless Infra (APs)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "U6-LR-C0-Pacific DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.112" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "U6-LR-D0-Online DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.101" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "U6-LR-D0-Keuken DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.101" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "U6-LR-D0-Bistro DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.101" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
       ]
      },
      {
       "alias": "U6-LR-D0-CFO DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.101" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "U6-LR-C1-Mathias DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.112" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "U6-LR-D1-Keuken DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.112" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "5" }
       ]
      },
      {
       "alias": "U6-LR-D1-Arne DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.111" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "U6-LR-C2-Creatie DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.112" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "U6-LR-D1-Vergaderzalen DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.111" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "7" }
       ]
      },
      {
       "alias": "U6-LR-C1-Sales DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.111" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "U6-LR-D2-OM-Video DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.0.61" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "66" }
       ]
      },
      {
       "alias": "U6-LR-Printing DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "U6-LR-Fotostudio DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "4" }
       ]
      },
      {
       "alias": "U6-LR-Fitness DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.131" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "3" }
       ]
      },
      {
       "alias": "U6-LR-Zolder DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.131" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "U6-LR-Loods2 DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "1" }
       ]
      },
      {
       "alias": "U6-LR-Loods3 DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "5" }
       ]
      },
      {
       "alias": "U6-LR-Loods4-Laadkades DATA",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "snmp_if:traffic",
       "query": "SELECT non_negative_derivative(mean(\"bytes_rcvd\"), 1s) *8 AS \"$_device\", non_negative_derivative(mean(\"bytes_sent\"), 1s) *8 AS \"S0-01-to-Fortigate (OUT)\" FROM \"snmp_if:traffic\" WHERE (\"device\" = '192.168.0.61' AND \"if_index\" = '49') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "bytes_rcvd" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "IN" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "OUT" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "192.168.24.132" },
        { "condition": "AND", "key": "if_index", "operator": "=", "value": "2" }
       ]
      }
     ]
    }
   ]
  }
 ]
}